// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muuegovaingqcnywpwza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dWVnb3ZhaW5ncWNueXdwd3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4OTQ0MDAsImV4cCI6MjA4NzQ3MDQwMH0.wBU8xoxhADyTAxCmcvSHh687rIhh2zBrcWC-dfzDEdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});